- hosts: webservers
  gather_facts: no
  tasks:
    - name: list root webservers
      shell: ls /
      register: result
    - name: stdout
      debug:
        msg: "{{ result.stdout_lines }}"